issuer: http://localhost:5556/dex

storage:
  type: memory

web:
  http: 0.0.0.0:5556

staticClients:
  - id: marpledb-client
    redirectURIs:
      - "http://localhost:8002/callback"
    name: "MarpleDB"
    secret: marpledb-secret

enablePasswordDB: true
staticPasswords:
  - email: "admin@example.com"
    hash: "$2a$10$2b2cU8CPhOTaGrs1HRQuAueS7JTT5ZHsHSzYiFPm1leZck7Mc.Ygy" # Password: admin
    username: "admin"
    userID: "08a8684b-db88-4b73-90a9-3cd1661f5466"
