# This is the default configuration for running Marple on-premise
# A postgres in docker is included, but it is optional, see .env for configuration
# Please get in touch with support@marpledata.com for guidance and licensing
# docker-compose setup suited for Marple deployments (staging, saas)
services:
  marple:
    container_name: marple
    image: docker.marpledata.com/library/marple:$MARPLE_VERSION
    environment:
      - MARPLE_DEPLOYMENT=$MARPLE_DEPLOYMENT
      - MARPLE_PUBLIC_URL=$MARPLE_PUBLIC_URL
      - MARPLE_SUPERUSER_ID=$MARPLE_SUPERUSER_ID
      - MARPLE_SEND_MAIL=$MARPLE_SEND_MAIL
      - MARPLE_IS_OFFLINE=$MARPLE_IS_OFFLINE
      - MARPLE_AUTH0_DOMAIN=$MARPLE_AUTH0_DOMAIN
      - MARPLE_AUTH0_MARPLE_API_AUDIENCE=$MARPLE_AUTH0_MARPLE_API_AUDIENCE
      - MARPLE_AUTH0_MARPLE_APP_CLIENT_ID=$MARPLE_AUTH0_MARPLE_APP_CLIENT_ID
      - MARPLE_AUTO_JOIN_WORKSPACE=$MARPLE_AUTO_JOIN_WORKSPACE
      - MARPLE_TIMESCALE_HOST=$MARPLE_POSTGRES_HOST
      - MARPLE_TIMESCALE_PORT=$MARPLE_POSTGRES_PORT
      - MARPLE_TIMESCALE_DB_NAME=$MARPLE_POSTGRES_DB_NAME
      - MARPLE_TIMESCALE_PW=$MARPLE_POSTGRES_PW
      - MARPLE_TIMESCALE_USER=$MARPLE_POSTGRES_USER
      - MARPLE_MAX_INGESTION_DPS=$MARPLE_MAX_INGESTION_DPS
      - MARPLE_MAX_INGESTION_THREADS_GLOBAL=$MARPLE_MAX_INGESTION_THREADS_GLOBAL
      - MARPLE_MAX_INGESTION_THREADS_WORKSPACE=$MARPLE_MAX_INGESTION_THREADS_WORKSPACE
      - MARPLE_PLUGIN_MAX_RAM_MB=$MARPLE_PLUGIN_MAX_RAM_MB
    ports:
      - $MARPLE_PORT:80 # first port is host
    volumes:
      - $MARPLE_HOME:/srv/marple
      - $MARPLE_FILE_SYSTEM/file_server:/etc/file_server_volume
    depends_on:
      - postgres
    restart: unless-stopped

  postgres:
    container_name: marple-postgres
    image: postgres:14-alpine
    environment:
      - POSTGRES_USER=$MARPLE_POSTGRES_USER
      - POSTGRES_PASSWORD=$MARPLE_POSTGRES_PW
      - POSTGRES_DB=$MARPLE_POSTGRES_DB_NAME
      - TS_TUNE_MEMORY=$MARPLE_POSTGRES_RAM # = 25% if 4 GB RAM
    shm_size: 256mb
    volumes:
      - "$MARPLE_FILE_SYSTEM/db:/var/lib/postgresql/data"
    ports:
      - $MARPLE_POSTGRES_PORT:$MARPLE_POSTGRES_PORT
    expose:
      - $MARPLE_POSTGRES_PORT
    command: -p $MARPLE_POSTGRES_PORT
    restart: unless-stopped
